// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	ports "cache/objects/ports"

	mock "github.com/stretchr/testify/mock"
)

// CacheBuilder is an autogenerated mock type for the CacheBuilder type
type CacheBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields: evictionPolicy
func (_m *CacheBuilder) Build(evictionPolicy string) ports.CacheManager {
	ret := _m.Called(evictionPolicy)

	var r0 ports.CacheManager
	if rf, ok := ret.Get(0).(func(string) ports.CacheManager); ok {
		r0 = rf(evictionPolicy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.CacheManager)
		}
	}

	return r0
}
